<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KiwiCubed.Api\KiwiCubed.Api.csproj" />
    <ProjectReference Include="..\KiwiCubed.Engine\KiwiCubed.Engine.csproj" />
  </ItemGroup>

  <Target Name="CopyFastNoiseToServer" AfterTargets="Build">
  	<Copy SourceFiles="..\KiwiCubed.Engine\Dependencies\FastNoise.dll" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
